//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogs
    {
        public int LogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Action { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string IPAddress { get; set; }
        public string MachineName { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string Description { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
