//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestVehicles
    {
        public int GuestVehicleID { get; set; }
        public string LicensePlate { get; set; }
        public int VehicleTypeID { get; set; }
        public string DriverName { get; set; }
        public string DriverPhone { get; set; }
        public Nullable<int> VisitingApartmentID { get; set; }
        public string Purpose { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public string CheckInImage { get; set; }
        public string CheckOutImage { get; set; }
        public Nullable<int> SlotID { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> CheckInBy { get; set; }
        public Nullable<int> CheckOutBy { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
    
        public virtual Apartments Apartments { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ParkingSlots ParkingSlots { get; set; }
        public virtual VehicleTypes VehicleTypes { get; set; }
    }
}
