//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetails
    {
        public int DetailID { get; set; }
        public int InvoiceID { get; set; }
        public int VehicleID { get; set; }
        public int FeeID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
    
        public virtual ParkingFees ParkingFees { get; set; }
        public virtual Invoices Invoices { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
