//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int HistoryID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public string IPAddress { get; set; }
        public string MachineName { get; set; }
        public string LoginStatus { get; set; }
        public string FailReason { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
