//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingLogs
    {
        public int LogID { get; set; }
        public int VehicleID { get; set; }
        public Nullable<int> SlotID { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public string CheckInImage { get; set; }
        public string CheckOutImage { get; set; }
        public Nullable<int> CheckInBy { get; set; }
        public Nullable<int> CheckOutBy { get; set; }
        public string ParkingType { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string Note { get; set; }
        public string LogStatus { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ParkingSlots ParkingSlots { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
