//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagement.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkingManagementEntities : DbContext
    {
        public ParkingManagementEntities()
            : base("name=ParkingManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartments> Apartments { get; set; }
        public virtual DbSet<AuditLogs> AuditLogs { get; set; }
        public virtual DbSet<Buildings> Buildings { get; set; }
        public virtual DbSet<GuestVehicles> GuestVehicles { get; set; }
        public virtual DbSet<InvoiceDetails> InvoiceDetails { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<LoginHistory> LoginHistory { get; set; }
        public virtual DbSet<ParkingFees> ParkingFees { get; set; }
        public virtual DbSet<ParkingLogs> ParkingLogs { get; set; }
        public virtual DbSet<ParkingSlots> ParkingSlots { get; set; }
        public virtual DbSet<ParkingZones> ParkingZones { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Residents> Residents { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SystemConfigs> SystemConfigs { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vehicles> Vehicles { get; set; }
        public virtual DbSet<VehicleTypes> VehicleTypes { get; set; }
    }
}
