//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicles()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetails>();
            this.ParkingLogs = new HashSet<ParkingLogs>();
        }
    
        public int VehicleID { get; set; }
        public int ResidentID { get; set; }
        public int VehicleTypeID { get; set; }
        public Nullable<int> SlotID { get; set; }
        public string LicensePlate { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public Nullable<int> YearOfManufacture { get; set; }
        public string CardNumber { get; set; }
        public string VehicleImage { get; set; }
        public string LicensePlateImage { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetails> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingLogs> ParkingLogs { get; set; }
        public virtual ParkingSlots ParkingSlots { get; set; }
        public virtual Residents Residents { get; set; }
        public virtual VehicleTypes VehicleTypes { get; set; }
    }
}
